#!/bin/bash


function print_access_error()
{
	echo "You dont have permissions to write in " $INSTALL_DIR "."
	echo " Please:"
	echo "   + log as root or "
	echo "   + select a direcotory in which you have write and access"
	echo "     permisions, for example: ~/ciao \n\n"
}


while true; do

echo -ne "Install in: " ; read INSTALL_DIR 


if [ -e $INSTALL_DIR ] ; then
	echo "trying " $INSTALL_DIR
else
	echo -ne "Directory " $INSTALL_DIR " does not exsist,\nwould you like to create it (y/n)? "
	read CREATE
	
	if [ "y" = $CREATE ] ; then
	    mkdir -p $INSTALL_DIR
# || { print_access_error ; exit -1 ; }

	elif [ "n" = $CREATE ] ; then
	    true
        fi
fi

# Now check if we have permisions
if [ -w $INSTALL_DIR ] ; then
	echo "Directory: " $INSTALL_DIR " selected"
	break
else
       	print_access_error
fi

done