/* Do not edit - this file is automatically generated
   by foreign_inteface.pl ! */
#include "/home/clip/Systems/ciao/include/LINUXi86/datadefs.h"
#include "/home/clip/Systems/ciao/include/LINUXi86/support.h"
#include "/home/clip/Systems/ciao/lib/foreign_interface/foreign_interface.h"
void obtain_list(long,long*,char **);
BOOL prolog_obtain_list(Arg)
  Argdecl;
{
  REGISTER long v0;
  long v1;
  char * v2;
  REGISTER TAGGED p1;
  REGISTER TAGGED p2;
  GET_INTEGER(0,v0);
  obtain_list(v0,&v1,&v2);
  p1 = MakeInteger(Arg,v1);
  p2 = MakeList(Arg,v2,v1);
  FREE(v2);
  DEREF(X(1),X(1));
  if (!cunify(Arg,X(1),p1))
    return FALSE;
  DEREF(X(2),X(2));
  if (!cunify(Arg,X(2),p2))
    return FALSE;
  return TRUE;
}
void show_list(long,char *);
BOOL prolog_show_list(Arg)
  Argdecl;
{
  REGISTER long v0;
  REGISTER char * v1;
  GET_INTEGER(0,v0);
  BYTES_TEST(1,v1,v0);
  GET_BYTES(1,v1,v0);
  show_list(v0,v1);
  FREE(v1);
  return TRUE;
}
void byte_lists_init(module)
  char *module;
{
  FUNCTOR_DEFINITION_CODE
  define_c_mod_predicate(module,"obtain_list",prolog_obtain_list,3);
  define_c_mod_predicate(module,"show_list",prolog_show_list,2);
}
void byte_lists_end(module)
  char *module;
{
  undefine_c_mod_predicate(module,"obtain_list",3);
  undefine_c_mod_predicate(module,"show_list",2);
}
