/* Copyright (C) 1996,1997,1998, UPM-CLIP */

#include <stdio.h>

#include "datadefs.h"

#define ASFORM "\t%-16s= %-6d|  %s\n"
#define CCFORM "#define %-16s %-6d/* %s */\n"
#define PLFORM "eval32(%-16s,%-6d).  % %s\n"
#define FORM ASFORM

#define MI(S,F) (long)&S.F-(long)&S
#define NL printf("\n\n")

int main()
{
  struct worker w;
  struct node   n;
  struct frame  f;
/*  struct try_node t;*/
  struct definition d;

  printf("# /* Copyright (C) 1988, Swedish Institute of Computer Science. */\n\n");
  printf("# /* DO NOT EDIT THIS FILE */\n");
  printf("# /* it has been automatically generated by 'kernel_con'*/\n\n");

  printf(FORM,"node",MI(w,node),"B choice pointer");
  printf(FORM,"next_node",MI(w,next_node),"BB1 .. at predicate entry ");
  printf(FORM,"segment_node",MI(w,segment_node),"gc's segment choice point");
  printf(FORM,"insn",MI(w,insn),"P program counter");
  printf(FORM,"structure",MI(w,structure),"S structure pointer");
  printf(FORM,"global_uncond",MI(w,global_uncond),
              "HB first uncond. global variable");
  printf(FORM,"local_uncond",MI(w,local_uncond),
              "AB first uncond. local variable no.");
  printf(FORM,"value_trail",MI(w,value_trail),"size of value_trail ext. of w->node");
  printf(FORM,"trail_top",MI(w,trail_top),"TR trail pointer");
  printf(FORM,"global_top",MI(w,global_top),"H heap pointer");
  printf(FORM,"next_alt",MI(w,next_alt),"P' next clause at predicate entry");
  printf(FORM,"frame",MI(w,frame),"E environment pointer");
  printf(FORM,"next_insn",MI(w,next_insn),"L continuation");
  printf(FORM,"local_top",MI(w,local_top),
              "NewA local stack pointer, or NULL if invalid");
  printf(FORM,"Xbase",MI(w,term[0]),"X0-Xi temporary variables");
  NL;

  printf(FORM,"d_enter_instr",MI(d,enter_instr),"");
  printf(FORM,"d_arity",MI(d,arity),"");
  printf(FORM,"d_printname",MI(d,printname),"");
  printf(FORM,"d_properties",MI(d,properties),"");
  printf(FORM,"d_code",MI(d,code.incoreinfo),"");
  NL;

  printf(FORM,"ARITYLIMIT",ARITYLIMIT,"");
  printf(FORM,"CHOICEPAD",CHOICEPAD,"");


  printf(FORM,"f_frame",MI(f,frame),"CE continuation frame pointer");
  printf(FORM,"f_next_insn",MI(f,next_insn),"CL continuation program pointer");
  printf(FORM,"f_term0",MI(f,term[0]),"Y0-Yi permanent variables");
  NL;

  printf(FORM,"n_trail_top",MI(n,trail_top),"TR' trail pointer");
  printf(FORM,"n_global_top",MI(n,global_top),"H' heap pointer");
  printf(FORM,"n_next_alt",MI(n,next_alt),"P' next clause at predicate entry");
  printf(FORM,"n_frame",MI(n,frame),"E' environment pointer");
  printf(FORM,"n_next_insn",MI(n,next_insn),"L'");
  printf(FORM,"n_local_top",MI(n,local_top),
              "A' local stack pointer, or NULL if invalid");
  printf(FORM,"n_term0",MI(n,term[0]),"X0-Xi");
  NL;

  exit(0);
}

#undef MI
#undef NL
#undef FORM
#undef ASFORM
#undef CCFORM
