/* Copyright (C) 1996,1997,1998, UPM-CLIP */

	case U2_YVAL_VOID:
		U1_YVAL_W(P1);
		U1_VOID_W(SP2);
		DISPATCH_W(2);

	case U2_YLVAL_VOID:
		U1_YLVAL_W(P1);
		U1_VOID_W(SP2);
		DISPATCH_W(2);

	case U2_YVAL_XVAR:
		U1_YVAL_W(P1);
		U1_XVAR_W(P2);
		DISPATCH_W(2);

	case U2_YLVAL_XVAR:
		U1_YLVAL_W(P1);
		U1_XVAR_W(P2);
		DISPATCH_W(2);

	case U2_YVAL_YVAR:
		U1_YVAL_W(P1);
		U1_YVAR_W(P2);
		DISPATCH_W(2);

	case U2_YLVAL_YVAR:
		U1_YLVAL_W(P1);
		U1_YVAR_W(P2);
		DISPATCH_W(2);

	case U2_YVAL_YFVAL:
		U1_YVAL_W(P1);
		U1_YFVAL_W(P2);
		DISPATCH_W(2);

	case U2_YLVAL_YFVAL:
		U1_YLVAL_W(P1);
		U1_YFVAL_W(P2);
		DISPATCH_W(2);

	case U2_YVAL_XVAL:
		U1_YVAL_W(P1);
		U1_XVAL_W(P2);
		DISPATCH_W(2);

	case U2_YVAL_XLVAL:
		U1_YVAL_W(P1);
		U1_XLVAL_W(P2);
		DISPATCH_W(2);

	case U2_YLVAL_XVAL:
		U1_YLVAL_W(P1);
		U1_XVAL_W(P2);
		DISPATCH_W(2);

	case U2_YLVAL_XLVAL:
		U1_YLVAL_W(P1);
		U1_XLVAL_W(P2);
		DISPATCH_W(2);

	case U2_YVAL_YVAL:
		U1_YVAL_W(P1);
		U1_YVAL_W(P2);
		DISPATCH_W(2);

	case U2_YVAL_YLVAL:
		U1_YVAL_W(P1);
		U1_YLVAL_W(P2);
		DISPATCH_W(2);

	case U2_YLVAL_YVAL:
		U1_YLVAL_W(P1);
		U1_YVAL_W(P2);
		DISPATCH_W(2);

	case U2_YLVAL_YLVAL:
		U1_YLVAL_W(P1);
		U1_YLVAL_W(P2);
		DISPATCH_W(2);
