/* Do not edit - this file is automatically generated
   by foreign_inteface.pl ! */
#include "/home/clip/Systems/ciao/include/LINUXi86/datadefs.h"
#include "/home/clip/Systems/ciao/include/LINUXi86/support.h"
#include "/home/clip/Systems/ciao/lib/foreign_interface/foreign_interface.h"
void * object(long);
BOOL prolog_object(Arg)
  Argdecl;
{
  REGISTER long v0;
  void * v1;
  REGISTER TAGGED p1;
  GET_INTEGER(0,v0);
  v1 = object(v0);
  p1 = MakeAddress(Arg,v1);
  DEREF(X(1),X(1));
  if (!cunify(Arg,X(1),p1))
    return FALSE;
  return TRUE;
}
void show_object(void *);
BOOL prolog_show_object(Arg)
  Argdecl;
{
  REGISTER void * v0;
  GET_ADDRESS(0,v0);
  show_object(v0);
  return TRUE;
}
void objects_init(module)
  char *module;
{
  FUNCTOR_DEFINITION_CODE
  define_c_mod_predicate(module,"object",prolog_object,2);
  define_c_mod_predicate(module,"show_object",prolog_show_object,1);
}
void objects_end(module)
  char *module;
{
  undefine_c_mod_predicate(module,"object",2);
  undefine_c_mod_predicate(module,"show_object",1);
}
