builtin_module(arithmetic).
builtin_module(atomic_basic).
builtin_module(attributes).
builtin_module(basic_props).
builtin_module(basiccontrol).
builtin_module(data_facts).
builtin_module(exceptions).
builtin_module(io_aux).
builtin_module(io_basic).
builtin_module(prolog_flags).
builtin_module(streams_basic).
builtin_module(system_info).
builtin_module(term_basic).
builtin_module(term_compare).
builtin_module(term_typing).
