include ../../SETTINGS
include ../../SHARED

exports:
	$(SETLOCALCIAO) $(CIAOC) -x $(SRC)/lib/compiler/browse_builtins.pl
	$(SETLOCALCIAO) $(SRC)/lib/compiler/browse_builtins


distclean:
	/bin/rm -rf *.dep *.po *.asr
	/bin/rm -rf TAGS
