/* Do not edit - this file is automatically generated
   by foreign_inteface.pl ! */
#include "/home/clip/Systems/ciao/include/LINUXi86/datadefs.h"
#include "/home/clip/Systems/ciao/include/LINUXi86/support.h"
#include "/home/clip/Systems/ciao/lib/foreign_interface/foreign_interface.h"
BOOL prolog_i_am_native(struct worker *w);
void test_init(module)
  char *module;
{
  FUNCTOR_DEFINITION_CODE
  define_c_mod_predicate(module,"i_am_native",prolog_i_am_native,1);
}
void test_end(module)
  char *module;
{
  undefine_c_mod_predicate(module,"i_am_native",1);
}
