/* Do not edit - this file is automatically generated
   by foreign_inteface.pl ! */
#include "/home/clip/Systems/ciao/include/LINUXi86/datadefs.h"
#include "/home/clip/Systems/ciao/include/LINUXi86/support.h"
#include "/home/clip/Systems/ciao/lib/foreign_interface/foreign_interface.h"
char * get_static_str();
BOOL prolog_a_string(Arg)
  Argdecl;
{
  char * v0;
  REGISTER TAGGED p0;
  v0 = get_static_str();
  p0 = MAKE_STRING(Arg,v0);
  DEREF(X(0),X(0));
  if (!cunify(Arg,X(0),p0))
    return FALSE;
  return TRUE;
}
char * get_str(long);
BOOL prolog_lookup_string(Arg)
  Argdecl;
{
  REGISTER long v0;
  char * v1;
  REGISTER TAGGED p1;
  GET_INTEGER(0,v0);
  v1 = get_str(v0);
  p1 = MAKE_STRING(Arg,v1);
  FREE(v1);
  DEREF(X(1),X(1));
  if (!cunify(Arg,X(1),p1))
    return FALSE;
  return TRUE;
}
char * get_str(long);
BOOL prolog_lookup_atom(Arg)
  Argdecl;
{
  REGISTER long v0;
  char * v1;
  REGISTER TAGGED p1;
  GET_INTEGER(0,v0);
  v1 = get_str(v0);
  p1 = MAKE_ATOM(Arg,v1);
  FREE(v1);
  DEREF(X(1),X(1));
  if (!cunify(Arg,X(1),p1))
    return FALSE;
  return TRUE;
}
void put_str(char *);
BOOL prolog_show_string(Arg)
  Argdecl;
{
  REGISTER char * v0;
  STRING_TEST(0,v0);
  GET_CSTRING_FROM_LIST(0,v0);
  put_str(v0);
  FREE(v0);
  return TRUE;
}
void put_str(char *);
BOOL prolog_show_atom(Arg)
  Argdecl;
{
  REGISTER char * v0;
  GET_CSTRING_FROM_ATOM(0,v0);
  put_str(v0);
  FREE(v0);
  return TRUE;
}
void strings_and_atoms_init(module)
  char *module;
{
  FUNCTOR_DEFINITION_CODE
  define_c_mod_predicate(module,"a_string",prolog_a_string,1);
  define_c_mod_predicate(module,"lookup_string",prolog_lookup_string,2);
  define_c_mod_predicate(module,"lookup_atom",prolog_lookup_atom,2);
  define_c_mod_predicate(module,"show_string",prolog_show_string,1);
  define_c_mod_predicate(module,"show_atom",prolog_show_atom,1);
}
void strings_and_atoms_end(module)
  char *module;
{
  undefine_c_mod_predicate(module,"a_string",1);
  undefine_c_mod_predicate(module,"lookup_string",2);
  undefine_c_mod_predicate(module,"lookup_atom",2);
  undefine_c_mod_predicate(module,"show_string",1);
  undefine_c_mod_predicate(module,"show_atom",1);
}
