(setq refs-alist '(
   ("Sicstus-library" "AAF91")
   ("E-overview" "AKNL86")
   ("ben-ari" "BA82")
   ("BoByPeWa81" "BBP81")
   ("Byrd80" "Byr80")
   ("Sicstus" "Car88")
   ("radioweb-D3.1.M2-A2" "CCG98")
   ("pillow-www6" "CH97")
   ("radioweb-D3.1.M1-A1" "CHGT98")
   ("pillow-ws" "CHV96")
   ("iso-prolog" "DEDC96")
   ("dijkstra-semaphores" "Dij65")
    ("radioweb-D3.1.M2-A3" "GCH98")
   ("sicstus-scripts-complangprolog-www" "Her96")
   ("lpdoc-tr" "Her99")
   ("holzbaur-phd" "Hol90")
   ("holzbaur-plilp92" "Hol92")
    ("holzbaur-clone" "Hol94")
   ("knuth-lit" "Knu84")
   ("radioweb-ta" "Par97")
   ("Sicstus3" "Swe95")
))
